name: SwiftEvents
version: 1.0.6
main: com.swiftevents.SwiftEventsPlugin
api-version: 1.21
authors: [phitsee]
description: A comprehensive event system for PaperMC servers
website: https://github.com/phitzy/SwiftEvents

commands:
  swiftevent:
    description: Main SwiftEvents command
    usage: /swiftevent <sub-command> [args]
    aliases: [swe, se, ev]
    permission: swiftevents.user.base

permissions:
  swiftevents.*:
    description: Grants all permissions for the SwiftEvents plugin.
    children:
      swiftevents.admin: true
      swiftevents.user: true
      swiftevents.bypass.*: true

  swiftevents.user:
    description: Grants all user-level permissions.
    default: true
    children:
      swiftevents.user.base: true
      swiftevents.user.help: true
      swiftevents.user.list: true
      swiftevents.user.join: true
      swiftevents.user.leave: true
      swiftevents.user.tp: true
      swiftevents.user.stats: true
      swiftevents.hud.toggle: true
      swiftevents.event.pvp: true
      swiftevents.event.treasure: true
      swiftevents.event.building: true
      swiftevents.event.racing: true
      swiftevents.event.custom: true

  swiftevents.admin:
    description: Grants all administrative permissions.
    default: op
    children:
      swiftevents.user: true
      swiftevents.reload: true
      swiftevents.updatecheck: true
      swiftevents.admin.create: true
      swiftevents.admin.delete: true
      swiftevents.admin.edit: true
      swiftevents.admin.start: true
      swiftevents.admin.stop: true
      swiftevents.admin.clone: true
      swiftevents.admin.setpos: true
      swiftevents.admin.toggle: true
      swiftevents.admin.participants: true
      swiftevents.admin.tasker.*: true
      swiftevents.bypass.*: true
      swiftevents.hud.toggle: true

  # General Permissions
  swiftevents.reload:
    description: Allows reloading the plugin's configuration.
    default: op
  swiftevents.updatecheck:
    description: Allows checking for plugin updates.
    default: op
  swiftevents.hud:
    description: Receive HUD notifications
    default: true
  swiftevents.hud.toggle:
    description: Allows toggling the HUD display
    default: true
  swiftevents.chat:
    description: Receive chat notifications
    default: true
  swiftevents.sounds:
    description: Hear event sound effects
    default: true

  # User Permissions
  swiftevents.user.base:
    description: Basic permission to use the /swiftevent command.
    default: true
  swiftevents.user.help:
    description: Allows using the help command.
    default: true
  swiftevents.user.list:
    description: Allows listing available events.
    default: true
  swiftevents.user.join:
    description: Allows joining events.
    default: true
  swiftevents.user.leave:
    description: Allows leaving events.
    default: true
  swiftevents.user.tp:
    description: Allows teleporting to an event.
    default: op
  swiftevents.user.stats:
    description: Allows viewing event statistics.
    default: true

  # Admin Permissions
  swiftevents.admin.create:
    description: Allows creating new events.
    default: op
  swiftevents.admin.delete:
    description: Allows deleting events.
    default: op
  swiftevents.admin.edit:
    description: Allows editing existing events.
    default: op
  swiftevents.admin.start:
    description: Allows manually starting events.
    default: op
  swiftevents.admin.stop:
    description: Allows manually stopping events.
    default: op
  swiftevents.admin.clone:
    description: Allows cloning existing events.
    default: op
  swiftevents.admin.setpos:
    description: Allows setting event locations.
    default: op
  swiftevents.admin.toggle:
    description: Allows toggling event properties.
    default: op
  swiftevents.admin.participants:
    description: Allows managing event participants.
    default: op

  # Tasker Permissions
  swiftevents.admin.tasker.*:
    description: Grants all permissions for the event tasker.
    default: op
    children:
      swiftevents.admin.tasker.start: true
      swiftevents.admin.tasker.stop: true
      swiftevents.admin.tasker.restart: true
      swiftevents.admin.tasker.next: true
      swiftevents.admin.tasker.status: true
  swiftevents.admin.tasker.start:
    description: Allows starting the event tasker.
    default: op
  swiftevents.admin.tasker.stop:
    description: Allows stopping the event tasker.
    default: op
  swiftevents.admin.tasker.restart:
    description: Allows restarting the event tasker.
    default: op
  swiftevents.admin.tasker.next:
    description: Allows forcing the next event from the tasker.
    default: op
  swiftevents.admin.tasker.status:
    description: Allows checking the status of the event tasker.
    default: op

  # Event Type Permissions
  swiftevents.event.pvp:
    description: Permission to join PvP events.
    default: true
  swiftevents.event.treasure:
    description: Permission to join treasure hunt events.
    default: true
  swiftevents.event.building:
    description: Permission to join building events.
    default: true
  swiftevents.event.racing:
    description: Permission to join racing events.
    default: true
  swiftevents.event.custom:
    description: Permission to join custom type events.
    default: true

  # Bypass Permissions
  swiftevents.bypass.*:
    description: Grants all bypass permissions.
    default: op
    children:
      swiftevents.bypass.cooldown: true
      swiftevents.bypass.maxevents: true
  swiftevents.bypass.cooldown:
    description: Bypass the cooldown for joining events.
    default: op
  swiftevents.bypass.maxevents:
    description: Bypass the maximum number of concurrent events a player can join.
    default: op

  # Feature-specific permissions
  swiftevents.notify:
    description: Receive event notifications
    default: true